image: "rust:latest"

stages:
  - fmt
  - test

variables:
  NUSHELL_ARCH: "x86_64-unknown-linux-musl"
  NUSHELL_VERSION: "0.95.0"

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^(draft|no-ci):/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: ($CI_PIPELINE_SOURCE == "push") && ($CI_COMMIT_BRANCH == "main")

fmt:
  stage: fmt

  script:
    - make fmt-check

test:
  stage: test
  needs:
    - fmt
  before_script:
    - apt update --yes
    - apt upgrade --yes
    - apt install protobuf-compiler --yes

    - export NUSHELL_BUILD="nu-$NUSHELL_VERSION-$NUSHELL_ARCH"
    - export PATH="/tmp/:$PATH"

    # install Nushell
    - curl -fLo /tmp/nu.tar.gz "https://github.com/nushell/nushell/releases/download/$NUSHELL_VERSION/$NUSHELL_BUILD.tar.gz"
    - tar xvf /tmp/nu.tar.gz --directory /tmp
    - cp "/tmp/$NUSHELL_BUILD/nu" /tmp/nu

    - git submodule set-url -- komodo "https://gitlab-ci-token:${KOMODO_TOKEN}@gitlab.isae-supaero.fr/dragoon/komodo"
    - make init
    - make show

  script:
    - make check clippy
    - echo "HTTP_PROXY = ${HTTP_PROXY}"
    - echo "http_proxy = ${http_proxy}" 
    - echo "HTTPS_PROXY = ${HTTPS_PROXY}"
    - echo "https_proxy = ${https_proxy}"
    - unset HTTP_PROXY
    - unset http_proxy
    - unset HTTPS_PROXY
    - unset https_proxy
    - echo "HTTP_PROXY = ${HTTP_PROXY}"
    - echo "http_proxy = ${http_proxy}" 
    - echo "HTTPS_PROXY = ${HTTPS_PROXY}"
    - echo "https_proxy = ${https_proxy}"
    - export RUST_LOG=ERROR
    - make test
