[package]
name = "dragoonfly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = { default-features = false, features = ["identify", "request-response", "kad", "noise", "ping", "yamux"], version = "=0.51.0" }
libp2p-identity = { version = "0.2.7", features = ["ed25519", "rand","peerid"] }
libp2p-request-response = { version = "0.24.0"}
libp2p-swarm = { version = "0.42.0" , features=["macros"]}
async-trait = { version = "0.1.74", features = [] }


