[package]
name = "dragoonfly"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["semi-avid-pc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = { default-features = false, features = ["identify", "request-response", "kad", "noise", "ping", "yamux", "tcp", "dns", "async-std", "websocket", "mplex"], version = "=0.51.0" }
libp2p-noise = { version = "=0.42.0"}
libp2p-core = "=0.39.0"
libp2p-identify = { version = "=0.42.0"}
libp2p-identity = { version = "=0.2.7", features = ["ed25519", "rand","peerid"] }
libp2p-request-response = { version = "0.24.0"}
libp2p-swarm = { version = "=0.42.0" , features=["macros"]}
libp2p-kad = { version = "=0.43.0"}
async-trait = { version = "0.1.74", features = [] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
futures = "0.3"
axum = "0.6.20"
serde = { version = "1.0.192", features = ["derive"] }
regex = "1.10.2"
thiserror = "1.0.50"
serde_json = "1.0.108"
